NAME = DISCORD
DESCRIPTION = "Discord on the CE"
ICON = icon.png

COMPRESSED = YES
ARCHIVED = YES
			
HAS_PRINTF = NO
MAKE_GFX = cd $(GFXDIR) && $(CONVIMG)

CFLAGS = -Wall -Wextra -Oz

include $(shell cedev-config --makefile)